KEYWORDS = {
    'GANGS': [
        'abertos', 'aca', 'accu', 'agc', 'amigos dos amigos', 'amigos para sempre',
        'anti-disturbances squadron', 'armed farmers', 'army of national liberation', 'auc',
        'autodefensas gaitanistas de colombia', 'autodefesas unidas da colombia',
        'autodefesas unidas da colombia', 'awa', 'bacrim', 'bala na cara', 'bandas criminales',
        'bandera roja', 'barrio 5', 'bdm', 'black revenge', 'bloque central bolivar', 'bloque meta',
        'bonde de jesus', 'bonde do ecko', 'bonde do maluco', 'bonde dos 13', 'bonde dos 30',
        'bonde dos 40', 'bonde dos ajeita', 'bonde dos maluco', 'buxton gang', 'cali cartel', 'cangaco',
        'carecas do abc', 'carteis de drogas', 'cartel de drogas', 'cartel de los soles',
        'cartel do norte', 'cauca regional indigenous council', 'clan del golfo',
        'clan giraldo', 'clan usuga', 'coconuco', 'comando classe a', 'comando da laje', 'comando da paz',
        'comando organizado do maranhao', 'comando pelo certo',
        'comando revolucionario brasileiro da criminalidade', 'comando vermelho', 'comando vermelho jovem',
        'comboio do cao', 'crias da triplice', 'cric', 'criminal gangs', 'cumbre agraria', 'dois irmaos',
        'ejercito del mariscal lopez', 'ejercito del pueblo paraguayo', 'el dorado', 'eln', 'eml', 'epl',
        'epp', 'equipe real', 'equipe rex', 'escuadron movil antidisturbios', 'esmad',
        'exercito de libertacao nacional', 'familia do norte', 'familia do norte', 'familia monstro',
        'familia terror do amapa', 'farc', 'farrapos', 'fazendeiros armados', 'fdn',
        'forca revolucionaria catarinense', 'forcas armadas irregulares da colombia',
        'forcas armadas revolucionarias da colombia', 'forcas armadas revolucionarias da colombia',
        'forcas de autodefesa gaitanistas da colombia', 'franco supporters', 'ftc',
        'fuerza de tarea conjunta', 'gaitanist self-defense forces of colombia', 'gang a', 'gde',
        'gran colombia gold', 'grupo america', 'grupo k2', 'grupos criminosos', 'grupos neo',
        'guangue del pavilion I', 'guangue do barriga', 'guangue do sujeirinha', 'guardioes do estado',
        'guardioes do estado', 'huaorani', 'ifara', 'irregular armed forces of colombia',
        'joint task force', 'katiara', 'la empresa', 'la siberia', 'laimes', 'libertadores del vichada',
        'liga da justica', 'liga da justica', 'local miners', 'los caparrapos', 'los choros', 'los lobos',
        'los machos', 'los pachenca', 'los paisas', 'los pelusos', 'los pepes', 'los puntilleros',
        'los rastrojos', 'los rodos', 'los urabenos', 'lugo supporters', 'mafia do lixo de maceio',
        'mafia dos vampiros', 'mafia paranaense', 'mafia tocantinense', 'mapuche milicia', 'mata rindo',
        'medellin cartel', 'mercado do povo atitude', 'mesa minera', 'mobile anti-disturbances squadron',
        'movimento revolucionario tupac amaru', 'mrta',
        'national organization of indigenous people of colombia', 'novo cangaco', 'oaqachas',
        'oficina del caribe', 'okaida', 'onic', 'ordem e progresso',
        'organizacao nacional dos povos indigenas da colombia', 'os manos', 'os tauras', 'paez',
        "paraguayan people's army", 'pcc', "people's army of paraguay", 'pgc', 'pranato',
        'primeiro comando da capital', 'primeiro comando de vitoria', 'primeiro comando do maranhao',
        'primeiro comando do panda', 'primeiro crime revolucionario catarinense',
        'primeiro grupo catarinense', 'primeiro grupo catarinense', 'primeiro grupo catarinense',
        'quadrilha do sujeirinha', 'renacer', 'revolutionary armed forces of colombia', 'sabaneta',
        'sendero luminoso', 'sindicato do crime', 'sindicato do crime do rio grande do norte',
        'sindicato do rio grande do norte', 'sindicato do rn', 'sindicato rn', 'tagaeri', 'tandera milicia',
        'terceiro comando', 'terceiro comando da capital', 'terceiro comando jovem', 'terceiro comando puro',
        'the clan del golfo', 'the gulf clan', 'trem bala', 'tren de aragua', 'uniao do crime do amapa',
        'uniao do norte', 'unidos pela paz', 'vandalos', 'waorani', 'zinho milicia'
    ],
    'ORGANIZED CRIME': [
        'bicheiro',
        'bicheiros',
        'cartel',
        'cartéis',
        'crime coordenado',
        'crime organizado',
        'facção',
        'facções',
        'gangue armada',
        'gangue criminosa',
        'gangues armadas',
        'gangues criminosas',
        'grupo armado',
        'grupos armados',
        'grupos criminosos',
        'grupo faccionado',
        'grupos criminosos',
        'grupos faccionados',
        'jogo do bicho',
        'miliciano',
        'milicianos',
        'milícia',
        'milícias',
        'máfia',
        'máfias',
        'organização criminosa',
        'organizações criminosas',
        'quadrilha',
        'quadrilhas',
        'sindicatos do crime',
        'traficante',
        'traficantes'],
    'DRUGS': [
        "apreensao",
        "cocaina",
        "droga",
        "fentanil",
        "hidrocloreto de cocaina", # ****
        "maconha",
        "oxicodona",
        "oxi",
        "pasta base",
        "papelote",
        "pino",
        "skunk",
        "skank",
        "trafico",
        "traficante",
        "tijolo",
    ],
    'ARMED INTERACTIONS': [
        'assassinato',
        'carnificina',
        'chacina',
        'confronto', 
        'enfrentamento', 
        'extermínio', 
        'fuzilamento', 
        'guerra do trafico', 
        'homicidio', 
        'massacre', 
        'morta', 
        'morte', 
        'morto', 
        'queima de arquivo'
    ]
}

VALIDATION_KEYWORDS = {
    'GANGS': [
        r'\babertos\b', r'\baca\b', r'\baccu\b', r'\bagc\b', r'\bamigos\s*dos\s*amigos\b',
        r'\bamigos\s*para\s*sempre\b', r'\banti-disturbances\s*squadron\b', r'\barmed\s*farmers\b',
        r'\barmy\s*of\s*national\s*liberation\b', r'\bauc\b', r'\bautodefensas\s*gaitanistas\s*de\s*colombia\b',
        r'\bautodefesas\s*unidas\s*da\s*colombia\b', r'\bautodefesas\s*unidas\s*da\s*colombia\b', r'\bawa\b',
        r'\bbacrim\b', r'\bbala\s*na\s*cara\b', r'\bbandas\s*criminales\b', r'\bbandera\s*roja\b',
        r'\bbarrio\s*5\b', r'\bbdm\b', r'\bblack\s*revenge\b', r'\bbloque\s*central\s*bolivar\b',
        r'\bbloque\s*meta\b', r'\bbonde\s*de\s*jesus\b', r'\bbonde\s*do\s*ecko\b', r'\bbonde\s*do\s*maluco\b', 
        r'\bbonde\s*dos\s*13\b', r'\bbonde\s*dos\s*30\b', r'\bbonde\s*dos\s*40\b', r'\bbonde\s*dos\s*ajeita\b', 
        r'\bbonde\s*dos\s*maluco\b', r'\bbuxton\s*gang\b', r'\bcali\s*cartel\b', r'\bcangaco\b', 
        r'\bcarecas\s*do\s*abc\b', r'\bcarteis\s*de\s*drogas\b', r'\bcartel\s*de\s*drogas\b', 
        r'\bcartel\s*de\s*los\s*soles\b', r'\bcartel\s*do\s*norte\b', 
        r'\bcauca\s*regional\s*indigenous\s*council\b', r'\bclan\s*del\s*golfo\b', 
        r'\bclan\s*giraldo\b', r'\bclan\s*usuga\b', r'\bcoconuco\b', r'\bcomando\s*classe\s*a\b', 
        r'\bcomando\s*da\s*laje\b', r'\bcomando\s*da\s*paz\b', r'\bcomando\s*organizado\s*do\s*maranhao\b', 
        r'\bcomando\s*pelo\s*certo\b', r'\bcomando\s*revolucionario\s*brasileiro\s*da\s*criminalidade\b', 
        r'\bcomando\s*vermelho\b', r'\bcomando\s*vermelho\s*jovem\b', r'\bcomboio\s*do\s*cao\b', 
        r'\bcrias\s*da\s*triplice\b', r'\bcric\b', r'\bcriminal\s*gangs\b', r'\bcumbre\s*agraria\b', 
        r'\bdois\s*irmaos\b', r'\bejercito\s*del\s*mariscal\s*lopez\b', r'\bejercito\s*del\s*pueblo\s*paraguayo\b', 
        r'\bel\s*dorado\b', r'\beln\b', r'\beml\b', r'\bepl\b', r'\bepp\b', r'\bequipe\s*real\b', 
        r'\bequipe\s*rex\b', r'\bescuadron\s*movil\s*antidisturbios\b', r'\besmad\b', 
        r'\bexercito\s*de\s*libertacao\s*nacional\b', r'\bfamilia\s*do\s*norte\b', r'\bfamilia\s*do\s*norte\b', 
        r'\bfamilia\s*monstro\b', r'\bfamilia\s*terror\s*do\s*amapa\b', r'\bfarc\b', r'\bfarrapos\b', 
        r'\bfazendeiros\s*armados\b', r'\bfdn\b', r'\bforca\s*revolucionaria\s*catarinense\b', 
        r'\bforcas\s*armadas\s*irregulares\s*da\s*colombia\b', 
        r'\bforcas\s*armadas\s*revolucionarias\s*da\s*colombia\b', 
        r'\bforcas\s*armadas\s*revolucionarias\s*da\s*colombia\b', 
        r'\bforcas\s*de\s*autodefesa\s*gaitanistas\s*da\s*colombia\b', r'\bfranco\s*supporters\b', r'\bftc\b', 
        r'\bfuerza\s*de\s*tarea\s*conjunta\b', r'\bgaitanist\s*self-defense\s*forces\s*of\s*colombia\b', 
        r'\bgang\s*a\b', r'\bgde\b', r'\bgran\s*colombia\s*gold\b', r'\bgrupo\s*america\b', r'\bgrupo\s*k2\b', 
        r'\bgrupos\s*criminosos\b', r'\bgrupos\s*neo\b', r'\bguangue\s*del\s*pavilion\s*I\b', 
        r'\bguangue\s*do\s*barriga\b', r'\bguangue\s*do\s*sujeirinha\b', r'\bguardioes\s*do\s*estado\b', 
        r'\bguardioes\s*do\s*estado\b', r'\bhuaorani\b', r'\bifara\b', 
        r'\birregular\s*armed\s*forces\s*of\s*colombia\b', r'\bjoint\s*task\s*force\b', r'\bkatiara\b', 
        r'\bla\s*empresa\b', r'\bla\s*siberia\b', r'\blaimes\b', r'\blibertadores\s*del\s*vichada\b', 
        r'\bliga\s*da\s*justica\b', r'\bliga\s*da\s*justica\b', r'\blocal\s*miners\b', r'\blos\s*caparrapos\b', 
        r'\blos\s*choros\b', r'\blos\s*lobos\b', r'\blos\s*machos\b', r'\blos\s*pachenca\b', 
        r'\blos\s*paisas\b', r'\blos\s*pelusos\b', r'\blos\s*pepes\b', r'\blos\s*puntilleros\b', 
        r'\blos\s*rastrojos\b', r'\blos\s*rodos\b', r'\blos\s*urabenos\b', r'\blugo\s*supporters\b', 
        r'\bmafia\s*do\s*lixo\s*de\s*maceio\b', r'\bmafia\s*dos\s*vampiros\b', r'\bmafia\s*paranaense\b', 
        r'\bmafia\s*tocantinense\b', r'\bmapuche\s*milicia\b', r'\bmata\s*rindo\b', r'\bmedellin\s*cartel\b', 
        r'\bmercado\s*do\s*povo\s*atitude\b', r'\bmesa\s*minera\b', r'\bmobile\s*anti-disturbances\s*squadron\b', 
        r'\bmovimento\s*revolucionario\s*tupac\s*amaru\b', r'\bmrta\b', 
        r'\bnational\s*organization\s*of\s*indigenous\s*people\s*of\s*colombia\b', r'\bnovo\s*cangaco\b', 
        r'\boaqachas\b', r'\boficina\s*del\s*caribe\b', r'\bokaida\b', r'\bonic\b', r'\bordem\s*e\s*progresso\b', 
        r'\borganizacao\s*nacional\s*dos\s*povos\s*indigenas\s*da\s*colombia\b',  r'\bos\s*manos\b', 
        r'\bos\s*tauras\b', r'\bpaez\b', r"\bparaguayan\s*people's\s*army\b", r'\bpcc\b', 
        r"\bpeople's\s*army\s*of\s*paraguay\b", r'\bpgc\b', r'\bpranato\b',
        r'\bprimeiro\s*comando\s*da\s*capital\b', r'\bprimeiro\s*comando\s*de\s*vitoria\b', 
        r'\bprimeiro\s*comando\s*do\s*maranhao\b', r'\bprimeiro\s*comando\s*do\s*panda\b', 
        r'\bprimeiro\s*crime\s*revolucionario\s*catarinense\b', r'\bprimeiro\s*grupo\s*catarinense\b', 
        r'\bprimeiro\s*grupo\s*catarinense\b', r'\bprimeiro\s*grupo\s*catarinense\b', 
        r'\bquadrilha\s*do\s*sujeirinha\b', r'\brenacer\b', 
        r'\brevolutionary\s*armed\s*forces\s*of\s*colombia\b', r'\bsabaneta\b', r'\bsendero\s*luminoso\b', 
        r'\bsindicato\s*do\s*crime\b', r'\bsindicato\s*do\s*crime\s*do\s*rio\s*grande\s*do\s*norte\b', 
        r'\bsindicato\s*do\s*rio\s*grande\s*do\s*norte\b', r'\bsindicato\s*do\s*rn\b', r'\bsindicato\s*rn\b', 
        r'\btagaeri\b', r'\btandera\s*milicia\b', r'\bterceiro\s*comando\b', 
        r'\bterceiro\s*comando\s*da\s*capital\b', r'\bterceiro\s*comando\s*jovem\b', 
        r'\bterceiro\s*comando\s*puro\b', r'\bthe\s*clan\s*del\s*golfo\b', r'\bthe\s*gulf\s*clan\b', 
        r'\btrem\s*bala\b', r'\btren\s*de\s*aragua\b', r'\buniao\s*do\s*crime\s*do\s*amapa\b', 
        r'\buniao\s*do\s*norte\b', r'\bunidos\s*pela\s*paz\b', r'\bvandalos\b', r'\bwaorani\b', 
        r'\bzinho\s*milicia\b'],
    'ORGANIZED CRIME': [
        r'\bbicheiros?\b',
        r'\bcarte(?:l|is)\b',
        r'\bcrime\s*coordenado\b',
        r'\bfacç(?:ao|oes)\b',
        r'\bgangues?\s*armadas?\b',
        r'\bgangues?\s*criminosas?\b',
        r'\bgrupos?\s*armados?\b',
        r'\bgrupos?\s*criminosos?\b',
        r'\bgrupos?\s*faccionados?\b',
        r'\bjogo\s*do\s*bicho\b',
        r'\bmilicianos?\b',
        r'\bmilicias?\b',
        r'\bmafias?\b',
        r'\borganizac(?:ao|oes)\s*criminosas?\b',
        r'\bquadrilhas?\b',
        r'\bsindicatos\s*do\s*crime\b',
        r'\btraficantes?\b',
    ],
    'DRUGS': [
        r'\bapreens(?:ao|oes)\b', 
        r'\bcocaina\b', 
        r'\bdrogas?\b', 
        r'\bfentanil\b', 
        r'\bhidrocloreto\s*de\s*cocaina\b', 
        r'\bmaconha\b',
        r'\boxi\b', 
        r'\boxicodona\b',
        r'\bpapelotes?\b',
        r'\bpasta\s*base\b',
        r'\bpinos?\b',
        r'\bskank\b',
        r'\bskunk\b',
        r'\btijolos?\b',
        r'\btraficantes?\b',
        r'\btraficos?\b'],
    'ARMED INTERACTIONS': [
        r'\bassassinatos?\b', 
        r'\bcarnificinas?\b', 
        r'\bchacinas?\b', 
        r'\bconfrontos?\b', 
        r'\benfrentamentos?\b', 
        r'\bexterminios?\b', 
        r'\bfuzilamentos?\b', 
        r'\bguerra\s*do\s*tráfico\b', 
        r'\bhomicidios?\b', 
        r'\bmassacres?\b', 
        r'\bmortas?\b', 
        r'\bmortes?\b', 
        r'\bmortos?\b', 
        r'\bqueima\s*de\s*arquivos?\b'
    ]
}
